 program: main.py
 method: grid
 metric:
   name: counterfactual_error/d_neq_dp_avg
   goal: minimize
 name: "case1"                # This is the name of the sweep
 project: "ICLR24-CameraReady-Simulated-Flow"  # This is the project the sweep should be placed under
 entity: "inouye-lab"

 parameters:
   f_type:
     values: ['dense','relax_cano']
   seed:
     values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
   batch_size:
     values: [500]
   n_domains:
     values: [2,3]
   model_depth:
     values: [4,8]
   k_spa:
     values: [2]
   int_set:
     values: ['4,5', '3,4', '2,3', '1,2', '0,1']
   latent_dim:
     values: [6]
   bias_scale:
     values: [1]
   step_check:
     values: [500]