program: main.py
method: grid
metric:
  name: "Test/CF-total"
  goal: minimize
name: "camera-ready"                # This is the name of the sweep
project: "ICLR24-CRMNIST"  # This is the project the sweep should be placed under
entity: "inouye-lab"

parameters:
  dataset:
    values: ['crmnist']
  model_preset:
    values: [1,2,3,4]
  seed:
    values: [1,2,3,4,5]
  latent_dim:
    values: [10]
  k_spa:
    values: [1,2,5]
  kld_scheduler:
    values: ['none']
  lamb_kld_start:
    values: [1000]  # If kld_scheduler is 'none', then lamb_kld_start will be the constant kld weight value
  num_iters:
    values: [300_000]
  step_save:
    values: [500]
  step_validate:
    values: [500]
  subsample:
    values: [True]

command:
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}
  - "--sweep"
  - "--note"
  - "iclrfinal"
  - "--save_dir"
  - "./ICLR/ICLR_models"
