 program: main.py
 method: grid
 metric:
   name: counterfactual_error/d_neq_dp_avg
   goal: minimize
 name: "case2"                # This is the name of the sweep
 project: "ICLR24-CameraReady-Simulated"  # This is the project the sweep should be placed under
 entity: "zyzhou"

 parameters:
   f_type:
     values: ['relax_can', 'dense']
   seed:
     values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
   batch_size:
     values: [500]
   n_domains:
     values: [2,3,10]
   k_spa:
     values: [1,2,3,4]
   int_set:
     values: ['5','4,5','3,4,5','2,3,4,5']
   latent_dim:
     values: [6]
   step_check:
     values: [100]